apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjavaimage-deploy
  labels:
   app: myjavaimage
spec:
   replicas: 2
   selector:
      matchLabels:
          app: myjavaimage
   template:
     metadata:
       labels:
        app: myjavaimage
     spec:
      containers:
      - name: myjavaimage-container
        image: shettypk/myjavaimage06june:1
        ports: 

        - containerPort: 8080