apiVersion: apps/v1
kind: Deployment
metadata:
  name: myloveimage-deploy
  labels:
   app: myloveimage
spec:
   replicas: 3
   selector:
      matchLabels:
          app: myloveimage
   template:
     metadata:
       labels:
        app: myloveimage
     spec:
      containers:
      - name: myjavaapp-container
        image: shettypk/myloveimage15me:1
        ports: 

        - containerPort: 8080