apiVersion: v1
kind: Service
metadata:
   name: myloveimage-svc
   labels:
     app: myloveimage
     
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
     app: myloveimage